### ISSUE TITLE
Burger shop glitched? 

### ISSUE THREAD

**Issue by 40-Cal-Banana** [ashjack/Sim-U-Kraft-Reloaded#24]
It doesnt fully build as shown here: http://imgur.com/P3O03je

**Comment by ashjack** [comment]
Fixed in 1.0.3

**Comment by Xalaber** [comment]
Its actually not fixed. I get the same exact problem.
![2015-04-02_14 44 03](https://cloud.githubusercontent.com/assets/4217389/6973323/3b896f1a-d947-11e4-9518-eaa9809bde84.png)
